### ISSUE TITLE
Problem in starting backend

### ISSUE THREAD

**Issue by pycleus** [rubberdok/indok-web#1499]
While using docker, I'm facing a problem regarding the backend. 
During composing, it says "exec /usr/src/app/entrypoints/integration.sh: no such file or directory". 
And while running migrate command, it says, "Container *** is restarting, wait until the container is running".

![Screenshot 2023-03-02 192550](https://user-images.githubusercontent.com/13154330/222611177-431db0ee-f73b-4dba-b54e-2e1cbe64a1d9.png)

**Comment by larwaa** [comment]
If you could post the exact steps you run to reproduce this error, it would be very helpful, and I'll take a look at the issue!

**Comment by pycleus** [comment]
As mentioned in the project setup, I followed as 
1. git clone
2. docker compose build
3. docker compose up
and then the problem occurs at step 8. Setup 10 is not working since the backend is not running.

**Comment by larwaa** [comment]
I'm unfortunately unable to reproduce the error locally, could you try to run
```zsh
# in indok-web/
docker compose -f docker-compose.yml build
docker compose -f docker-compose.yml up
```
and see if the error persists?

**Comment by pycleus** [comment]
I tried this but the error still exists.

**Comment by larwaa** [comment]
The `integration.sh` entrypoint should only be referenced in `docker-compose.integration.yml`, which should not be used for local development, so I'm just trying to nail down where things are going wrong here 😊 

Could you try running
```zsh
docker system prune
```
**NOTE:** this will remove all **unused containers, networks, images (both dangling and unreferenced)**, so if you have other unused docker images you wish to preserve, then consider following [this guide](https://www.freecodecamp.org/news/how-to-remove-images-in-docker/) instead to remove the containers and images associated with this project specifically.

and re-running the setup steps in the README, but running

```zsh
# in indok-web/
docker compose -f docker-compose.yml build
docker compose -f docker-compose.yml up
```
instead of just
```zsh
# in indok-web/
docker compose build
docker compose up
```

**Comment by pycleus** [comment]
Thanks for the details, however, the same error continues. FYI: I'm using windows 11 and local dev.
